// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyL-fjZBFtpx9898irmcvBuHhLQYcLxQY',
    appId: '1:765478026522:web:dac95174c6f7a9879440a3',
    messagingSenderId: '765478026522',
    projectId: 'meloplayer-6a79e',
    authDomain: 'meloplayer-6a79e.firebaseapp.com',
    storageBucket: 'meloplayer-6a79e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEzsOCL2a4TVyzR6RFP61OuWAiJOMOixg',
    appId: '1:765478026522:android:09369a58faa623709440a3',
    messagingSenderId: '765478026522',
    projectId: 'meloplayer-6a79e',
    storageBucket: 'meloplayer-6a79e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfInblw2G-a9d4qR3IrxMqVUAtxRqYGA',
    appId: '1:765478026522:ios:785c33f6a031a1599440a3',
    messagingSenderId: '765478026522',
    projectId: 'meloplayer-6a79e',
    storageBucket: 'meloplayer-6a79e.appspot.com',
    iosBundleId: 'com.example.meloPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUfInblw2G-a9d4qR3IrxMqVUAtxRqYGA',
    appId: '1:765478026522:ios:24e4877da36d36609440a3',
    messagingSenderId: '765478026522',
    projectId: 'meloplayer-6a79e',
    storageBucket: 'meloplayer-6a79e.appspot.com',
    iosBundleId: 'com.example.meloPlayer.RunnerTests',
  );
}
